const ONE_MINUTE_IN_MILLISECONDS = 60000;
const ONE_HOUR_IN_MILLISECONDS = 3600000;

const MAX_MESSAGE_LENGTH = 1000;
const MIN_MESSAGE_LENGTN = 1;

export {
  ONE_HOUR_IN_MILLISECONDS,
  ONE_MINUTE_IN_MILLISECONDS,
  MIN_MESSAGE_LENGTN,
  MAX_MESSAGE_LENGTH,
};
