version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    container_name: chat-app-nginx
    ports:
      - '3001:3001'
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - client
    networks:
      - chat-app-network

  client:
    build:
      dockerfile: Dockerfile.prod
      context: ./client
    container_name: chat-app-client
    command: yarn build
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - 3000:3000
    networks:
      - chat-app-network
    volumes:
      - ./client/src:/usr/src/app/src

  server:
    build:
      dockerfile: Dockerfile.prod
      context: ./server
    container_name: chat-app-server
    command: yarn start:prod
    restart: unless-stopped
    depends_on:
      - chat_db
    environment:
      - PORT=3002
    ports:
      - 3002:3002
    networks:
      - chat-app-network
    volumes:
      - ./server/src:/usr/src/app/src

  chat_db:
    image: mongo:latest
    container_name: chat-app-db
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: chat-app
    volumes:
      - mongo_db:/data/db
    networks:
      - chat-app-network

  peer_server:
    image: peerjs/peerjs-server
    container_name: chat-app-peer-server
    command: peerjs --port 9000
    restart: unless-stopped
    ports:
      - 9000:9000
    depends_on:
      - client
    networks:
      - chat-app-network

volumes:
  mongo_db:

networks:
  chat-app-network:
    driver: bridge
