version: '3'

services:
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    command: yarn start:dev

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    command: yarn start

  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
