const MAX_USERNAME_LENGTH = 50;
const MIN_USERNAME_LENGTH = 2;

const MAX_PASSWORD_LENGTH = 100;
const MIN_PASSWORD_LENGTH = 7;

const MAX_EMAIL_LENGTH = 100;

export {
  MAX_USERNAME_LENGTH,
  MIN_USERNAME_LENGTH,
  MAX_PASSWORD_LENGTH,
  MIN_PASSWORD_LENGTH,
  MAX_EMAIL_LENGTH,
};
